//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASN_Reimpresion
    {
        public int Id { get; set; }
        public int ASNId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual ASN ASN { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
